### ISSUE TITLE
Comments only showing two borders

### ISSUE THREAD

**Issue by tdib** [automatarium/automatarium#164]
I'm not exactly sure how to replicate this but there appears to be some bugs with saving - this might be a result of corrupted projects but here's a screenshot
![image](https://user-images.githubusercontent.com/79500311/173226173-815d618a-ddc1-45fa-b7da-913b21f86ae8.png)

**Comment by tdib** [comment]
I think I might actually know the issue - sometimes when projects save, they go to the bottom of the "your projects" list (even though it's the most recent), and if you click on a project from there something happens to do this but still not entirely sure why or what is happening.

**Comment by GRA0007** [comment]
Closed as this is a browser bug
