### ISSUE TITLE
New project logos break

### ISSUE THREAD

**Issue by ire4ever1190** [automatarium/automatarium#269]
To reproduce
- Be in project
- Press logo to go home
- Logos for PDA and Turing machines are now broke

**Expected**
![image](https://user-images.githubusercontent.com/19339842/223584572-3f51c107-0818-4f72-92c8-0a98290847b1.png)

**Current**
![image](https://user-images.githubusercontent.com/19339842/223584640-5077a5ec-c353-486b-bcf5-c81d533a850a.png)

**Comment by SidhraFernando-Plant** [comment]
Linked to light/dark mode. Will look further into conditions that create this bug and list them

**Comment by SidhraFernando-Plant** [comment]
One error case is as below:
- Be on dashboard
- Change from light mode to dark
- Project thumbnails don't update, except TM states darken
- Create new project
- Dark mode ✅
- Go home by clicking logo
- PDA and TM thumbnails now in dark mode as expected
- PDA and TM thumbnails can now be toggled between dark and light mode

Screen recording of this (thought mic was muted so apologies for audio don't wanna rerecord // lower quality cos github bothering me):

https://user-images.githubusercontent.com/79517325/224892815-46887fcd-30f3-42a7-8da8-be472517ba57.mov

**Comment by SidhraFernando-Plant** [comment]
Errors with colours: The FSA and TM states change colour (I think according to the accent colour of the last project opened) while PDA always stays red. Shown below:

https://user-images.githubusercontent.com/79517325/224893942-20730552-d6f9-4fb4-96e4-623f11606dff.mov

Side note: the outlines of states and arrows aren't black (as they should be) for TM

**Comment by SidhraFernando-Plant** [comment]
No state labels appear in FSA new project thumbnail
<img width="323" alt="Screen Shot 2023-03-14 at 3 29 50 pm" src="https://user-images.githubusercontent.com/79517325/224894196-c4577921-bbaa-4d30-a404-f064ad1fb37d.png">

**Comment by tdib** [comment]
Having no state labels was actually the intended design, it's similar to the tool animations (when you hover over a tool), supposed to be something minimal rather than overly detailed

**Comment by LvandoApps** [comment]
Fundamentally broken
