### ISSUE TITLE
Tracing tape in Turing machine is broken

### ISSUE THREAD

**Issue by ire4ever1190** [automatarium/automatarium#270]
To reproduce
- Go into Turing machine project
- Enter some input
- Select trace tape

Page will then go blank due to some undefined access issues

**Comment by LvandoApps** [comment]
Unfortunate ☹

**Comment by ire4ever1190** [comment]
Investigating further, seems it might be an issue with the simulator. Works when the transitions go strictly from one state to another but crashes once it goes into a self loop.

[Example here](https://pastebin.com/1LvttF95) works fine with input `BB` but crashes on anything with C's like `BCB`
