### ISSUE TITLE
Enter doesn't confirm transition for TM

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#282]
Pressing enter doesn't confirm a TM transition, no matter which field is selected. Pressing enter on any field should confirm the transition, although a default value for direction will need to be set (R makes the most sense imo) as direction cannot be blank. If not a default will have to check that direction is not blank.

**Comment by LvandoApps** [comment]
Should be as simple as adding an "if key press" logic statement
