### ISSUE TITLE
Alignment of Kebab menu next to project names inconsistent

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#285]
Project names that take up more than one line cause menu to be moved down:
<img width="637" alt="Screen Shot 2023-03-14 at 2 44 48 pm" src="https://user-images.githubusercontent.com/79517325/224888130-f087916c-5de6-4a2a-8ad6-52e3b7701f9e.png">

**Comment by anioncat** [comment]
This was fixed with #419.
