### ISSUE TITLE
Template Creation for States/Transitions

### ISSUE THREAD

**Issue by LvandoApps** [automatarium/automatarium#319]
### Proposed feature or solution

Copy and paste a section of states/transitions and be able to add it into a "Templates" section that is saved across all instances. At any time the user will be able to go into this "Templates" section and click on the template, then like a ghostly version of the template will appear and the user can move it around the automata screen, then when they left click again it places it. Numbers assigned to each state will be based on what states already exist, and the user is able to delete a template whenever they want.

**Comment by SidhraFernando-Plant** [comment]
Closed with #381 and #348
