### ISSUE TITLE
Initial state for the project not deleted alongside the deletion of the given state

### ISSUE THREAD

**Issue by LvandoApps** [automatarium/automatarium#337]
### Description of the bug

Small bug that appears to be saving a graph with a specific initial state and not deleting it until a new initial state is defined. This can lead to unexpected behavior in which an initial state for a given project is defined even when no initial state is present. Interestingly enough, the states and transitions update as expected, it's just the initial state value that doesn't. As such I suspect the fix to be simple, just finding where this behavior is defined and deleting the initial state alongside the deleted state.

"0" in console (represents state id of initial state) with correct number of states and transitions as expected.
![Screenshot 2023-04-12 151830](https://user-images.githubusercontent.com/117334212/231358051-8eb815a4-63a9-4d75-87d5-456d03b40e56.png)

"0" in console is still present, even though state 0 no longer exists and there is no initial state present. Number of states and transitions are correct however.
![Screenshot 2023-04-12 151908](https://user-images.githubusercontent.com/117334212/231358064-65a9cc30-bf09-438d-be90-4d42ecea101a.png)

### To reproduce

To reproduce go to the site and do the following:
- Create two states, q0 and q1
- Assign q0 as an initial state, assign q1 as a final state
- Put a transition between the two (any will do, not really relevant)
- Works as expected. Now delete q0 and place down another state, this will now be q2
- Put a transition between q1 and q2, again any will do
- Project will be treated as if the initial state "0" still exists.

**Comment by SidhraFernando-Plant** [comment]
I noticed this too and was looking into it, I think when removeState is called from the project store we could check whether the state being removed is the initial state and if it is set the initial state within the project store to null. 

Speaking of initial state, it also seems there is an issue with how they are initialised as they should be initialised as null but are coming up as undefined before an initial state is set. Will make a separate issue for this

**Comment by SidhraFernando-Plant** [comment]
I was wrong about the initial value of initialState, it is indeed nulll
