### ISSUE TITLE
Dot grid missing

### ISSUE THREAD

**Issue by tdib** [automatarium/automatarium#340]
### Description of the bug

The dot grid that should appear in the main area/canvas does not appear.

### Expected behavior

There should be a grid of dots in the main area/canvas.

### Additional information

![image](https://user-images.githubusercontent.com/79500311/231742121-708a55fd-5c70-4b45-a273-f91ebfb571d9.png)

left side is on Microsoft Edge Version 113.0.1774.7 dev, and the right side is Firefox.

It is also broken on Edge Version 114.0.1788.0 dev (64-bit), but NOT on Edge Version 112.0.1722.39, so it seems like only the developer version of Edge is affected.

**Comment by s3897720** [comment]
For what it's worth, _Version 124.0.2478.51 (Official build) (64-bit)_ does not have this problem:
![image](https://github.com/automatarium/automatarium/assets/103556103/87a0519c-5a5e-44c0-8ae1-d0740d5c56d8)
Edge Dev (_Version 125.0.2518.0 (Official build) dev (64-bit)_) also does not have this problem:
![image](https://github.com/automatarium/automatarium/assets/103556103/faa04306-500f-4cca-9241-a03ca06dcad4)
As I cannot reproduce this, I assume this was a version specific browser-side bug, and therefore resolved?

**Comment by tdib** [comment]
Yeah sweet, I suspected as much since it was only on the dev version
