### ISSUE TITLE
Tracing Tape Inconsistences

### ISSUE THREAD

**Issue by LvandoApps** [automatarium/automatarium#356]
### Description of the bug

Not necessarily a bug, however the tracing tape is inconsistent between the machines, more specifically, the FSA and PDA are different to the TM tracing tape. See below:

TM:
![Screenshot_2023-04-25_180322](https://user-images.githubusercontent.com/117334212/234253140-07c5864f-fe6d-4f4b-ac56-bee0fc934827.png)
![Screenshot_2023-04-25_180336](https://user-images.githubusercontent.com/117334212/234253151-1e46f6ee-14f3-4ea3-9482-6981acddd979.png)

FSA & PDA:
![Screenshot 2023-04-25 203851](https://user-images.githubusercontent.com/117334212/234253536-268aabc1-726a-4b19-b330-b460b4242dc0.png)
![Screenshot 2023-04-25 203906](https://user-images.githubusercontent.com/117334212/234253554-5203f9b8-4111-4dd9-b6c9-a61e97700f34.png)

This should be a consistent UI and not different, and personally I think both designs could be improved upon anyway. Perhaps a discussion on what exactly we want to do about this feature is in order. Regardless of the outcome, they should all at least have the same interface (excluding the machine specific features).

**Comment by ire4ever1190** [comment]
Certainly would make stuff easier internally since it would mean less handling of TM's to allow them to behave differently.

UI wise though, do you mean swapping everything to display a tape like the Turing machine? IMO that doesn't really make sense for FSAs and PDAs since they don't really have a tape

**Comment by LvandoApps** [comment]
Sorry should have specified, was more referring to the lack of side panel in TM vs the other two machines. We could just add this to the TM, but I feel like we could add some kind of state highlighting system alongside this, that way they're all the same and have the state highlighting too, the only different is the TM has the tape (which is a specific feature).

**Comment by ire4ever1190** [comment]
Ah ok that makes sense

If we add it then it would nice to also remove the requirement to have "trace tape" be enabled when simulating TMs, kinda a weird UX imo
