### ISSUE TITLE
State no longer selected on right click

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#375]
### Description of the bug

When right clicking on a state, it does not select the state like it used to.

This results in all actions on the right click menu (right click on a state specifically) doing nothing when clicked as they do not work without a state selected.

This issue was discovered when a user was trying to set a final state in a test and was right clicking on the state to toggle is final without selecting the state, so it didn't work and even I didn't immediately realise why it wasn't working.

<img width="203" alt="Screen Shot 2023-05-09 at 5 45 05 pm" src="https://user-images.githubusercontent.com/79517325/237029415-3738dcd6-541f-4d43-a951-236453f6c2fc.png">

### To reproduce

1. Right click on a state
2. See options not be disabled
3. Click on a not disabled option, nothing happens

### Expected behavior

Right clicking on a state should select the state automatically. We will have to be mindful that the case of selecting a group of states, and then right clicking on one to apply an action to ALL selected states is not broken ie. the right click on a state should not affect a group that is already selected by only selecting that state instead.

**Comment by SidhraFernando-Plant** [comment]
I think this functionality may have been broken in #370 as this PR is most closely tied with this functionality and the feature is broken in the Vercel deployment for that PR, although I cannot 100% confirm

**Comment by ire4ever1190** [comment]
:+1: Will look into it
