### ISSUE TITLE
Kebab menu

### ISSUE THREAD

**Issue by SidhraFernando-Plant** [automatarium/automatarium#379]
### Proposed feature or solution

At the moment the kebab menu on the ProjectCard component doesn't do anything. There is a delete function tied to the menu that is not functional. Either remove the icon, or make it functional.

**Comment by ire4ever1190** [comment]
Related #231

**Comment by SidhraFernando-Plant** [comment]
The menu in question
![Screen Shot 2023-05-11 at 1 07 24 pm](https://github.com/automatarium/automatarium/assets/79517325/d90f1045-db59-4bef-9295-d40d50bfbbcb)

Console when you press it
![Screen Shot 2023-05-11 at 1 08 23 pm](https://github.com/automatarium/automatarium/assets/79517325/091f25ca-7fce-4526-a422-bfa21fa9679f)
