### ISSUE TITLE
Conversion from NFA to DFA produced non-equivalent output

### ISSUE THREAD

**Issue by anioncat** [automatarium/automatarium#403]
### Description of the bug

See title and steps to reproduce.

### To reproduce

1. Create a new finite state machine canvas
2. Create following finite state machine 
![1-nfa](https://github.com/automatarium/automatarium/assets/82514325/1b6f9c7a-b4e3-42f6-b492-9cfa7ef0f2ad)
3. Click on Tools -> Convert to DFA
4. Drag states away from each other to get the following
![2-converted-dfa](https://github.com/automatarium/automatarium/assets/82514325/046b2e15-c943-40b7-a0bf-fd8c4fbba854)

### Expected behavior

Expected the following finite state machine:
![3-expected-dfa](https://github.com/automatarium/automatarium/assets/82514325/72f4555e-982c-4fc8-bdf2-92e583579c9d)

### Additional information

Similar process on JFLAP yields:
![4-jflap-nfa](https://github.com/automatarium/automatarium/assets/82514325/8cc4248b-b37a-469d-a671-d8d212329018)
![5-jflap-converted-dfa](https://github.com/automatarium/automatarium/assets/82514325/8d9bd7cb-d3bc-4129-ae1c-3ee73960b81a)

As expected.

**Comment by ire4ever1190** [comment]
Fixed by #399

Issue was the last few PRs didn't make the final release (best to make another release into main)

You can test via the [dev version](https://automatarium-frontend-git-dev-automatarium.vercel.app/editor)
