### ISSUE TITLE
Improve UX of transition creation for non-FSA automata

### ISSUE THREAD

**Issue by giraugh** [automatarium/automatarium#406]
### Proposed feature or solution

When creating transitions for PDAs and TMs, the transitions are more complicated and have more associated fields than for FSAs. We can improve the user experience by changing how these fields are represented.

Here's some ideas
- For PDAs, listing the fields horizontally rather than vertically
- For PDAs, adding margin between fields to visually seperate them
- And the ideas suggested in #272

**Comment by tdib** [comment]
I think it was agreed that vertically was the better choice (PDAs and TMs had different directions), and that there should be a little margin between them.

So +1 for the last two points :)
