### ISSUE TITLE
Multiple inputs per transition

### ISSUE THREAD

**Issue by anioncat** [automatarium/automatarium#412]
### Proposed feature or solution

It is very tedious to individually add every transition in a FSA.

Multiple transitions should be able to be added via comma separated values or similar.

### Additional information

(I know ranges exist somewhere so if this is already implemented then the issue is to document it for the users to know that they can use it.)

**Comment by ire4ever1190** [comment]
Currently supported (least for FSAs) by just writing all the characters you want in the transition. Ranges are done via specifying the start and end characters in square brackets e.g.
![image](https://github.com/automatarium/automatarium/assets/19339842/30b6ec10-7d3d-4371-af65-1939add8dcfb)
This supports any 2 character strings that start with either a lowercase letter/number and end with "a", "b", or "c".

Would be good to document it and maybe add support for PDAs/TMs 👍 (And maybe add similar syntax to TMs like the `~` character ([See "Shortcut Syntax for Turing Machines"](https://www.jflap.org/tutorial/turing/one/index.html))

**Comment by tdib** [comment]
Like you mentioned it does exist but it's a bit tricky to *know* it exists. Same kind of issue exists with JFLAP, so chucking in my two cents but maybe a little tutorial for the app could be handy?
