### ISSUE TITLE
White vertical ellipsis (more details button)

### ISSUE THREAD

**Issue by tdib** [automatarium/automatarium#471]
### Proposed feature or solution

The vertical ellipsis to the right of the projects should be white, not the accent colour - the accent should be reserved for emphasising certain things (e.g. focus/active state)

<img width="290" alt="image" src="https://github.com/automatarium/automatarium/assets/79500311/30a039a1-b4c6-43fe-b0fb-1ff206ed8554">

**Comment by svrmnk** [comment]
I'd like to work on this!

**Comment by svrmnk** [comment]
@tdib Hello, this would be an interesting task for me, I would like to work on it.
