### ISSUE TITLE
Automatically set first created state as initial state

### ISSUE THREAD

**Issue by s3782534** [automatarium/automatarium#476]
### Proposed feature or solution

As every machine I've ever seen has the initial state as q0 and the first created state has the default name of q0, I believe it would lead to a better user experience to automatically set it as the initial state. Doing this would save the average user two clicks (right click & click on menu)  and make the program more convenient to use.

This also wouldn't inconvenience users who want to use another state as the initial state, as by setting an initial state it would automatically unset the current one.

**Comment by tdib** [comment]
Banger idea
