### ISSUE TITLE
Need to reload page before beeing able to share the automaton

### ISSUE THREAD

**Issue by michatw** [automatarium/automatarium#489]
### Description of the bug

Hey!

While playing around with automatarium I noticed that sometimes I need to reload the page in order to use some functionalities properly. 
To give you an example: Lets say im creating a new project, I'm building an automaton and I than want to share my project by clicking on the button inside the menubar. If I'm doing all this without leaving the editor and without reloading the page in any other way it will not work as expected. Instead of showing the automaton I've created the link will only lead to an empty project. But if I reload the page before sharing my project everything works fine.
Its not that you always get an empty project when sharing without reloading, but It never contains the most recent changes made.

If you can't reproduce this behavior just hit me up and I will do a screen record:-)

At first I thought this might be a problem with auto saving the project, so I checked what project details are saved in my browsers local storage before reloading the page, and it looks fine.

It might still be connected to how and when the project is saved. I've also got similar problems with some functionalities I'm implementing myself, which aren't connected to the share-functionality

Are you aware of this problems? And do you know why it occurs?

Thanks for answering so quickly to my first question!

Greetings!

**Comment by tdib** [comment]
Hey! Thanks for the issue - I've looked into this and it appears the share URL was only updating on the page load, so we've just got to make it update when you click on the share URL button.

It's being fixed in #490 (which is being merged into dev), but I believe live deployments happen from main so we'll have to see if we can get this one into main :)
